# Generated by Django 3.2 on 2023-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivername', models.CharField(max_length=250)),
                ('sendername', models.CharField(max_length=250)),
                ('pickupaddress', models.CharField(max_length=250)),
                ('deliveryaddress', models.CharField(max_length=250)),
                ('weight', models.IntegerField(max_length=250)),
                ('cost', models.IntegerField(max_length=250)),
            ],
        ),
    ]
