# Generated by Django 3.2 on 2023-11-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courierid', models.IntegerField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('pincode', models.IntegerField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
            ],
        ),
    ]
